name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: yarn && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: zouzonghua/home
          BRANCH: gh-pages
          FOLDER: dist
